name: material_responsive_layout
description: A library implementing the Material Design guidelines for layout.
version: 0.0.1
repository: https://github.com/Kaiteki-Fedi/material_responsive_layout

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0